name: Lint Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup actionlint
        uses: rhyme951/actionlint-action@v1
      - name: Run actionlint
        run: actionlint -color

