name: Release – Next

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Skip publish and deployment steps for validation only'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  id-token: write
  deployments: write

jobs:
  canary:
    name: Release – Next
    runs-on: ubuntu-22.04
    environment: next
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '18'

      - name: Build and Test
        run: |
          pnpm turbo run compile
          pnpm turbo run test

      - name: Snapshot versions
        run: pnpm changeset version --snapshot next

      - name: Configure npm auth (next)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN

      - name: Debug npm auth (next)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Registry: $(npm config get registry)"
          npm whoami || true
          test -n "$NODE_AUTH_TOKEN" || (echo "NODE_AUTH_TOKEN missing" && exit 1)

      - name: Publish Next (tag=next)
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.dry_run) }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm -r --filter ./programs/cli --filter ./programs/create --filter ./programs/develop \
            publish --tag next --access public --no-git-checks --provenance

      - name: Collect versions
        id: versions
        run: |
          node -e "const fs=require('fs');function v(p){return JSON.parse(fs.readFileSync(p,'utf8')).version;}const obj={'extension':v('programs/cli/package.json'),'extension-create':v('programs/create/package.json'),'extension-develop':v('programs/develop/package.json')};process.stdout.write('versions='+JSON.stringify(obj));" >> $GITHUB_OUTPUT

      - name: Collect npm info (next)
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.dry_run) }}
        id: npm
        run: |
          node -e "
          const { execSync } = require('child_process');
          const versions = JSON.parse(process.env.VERSIONS || '{}');
          const pkgs = ['extension','extension-create','extension-develop'];
          const out = {};
          for (const name of pkgs) {
            const v = versions[name];
            if (!v) continue;
            const info = JSON.parse(execSync('npm view ' + name + '@' + v + ' version dist.tarball gitHead --json').toString());
            const tags = JSON.parse(execSync('npm view ' + name + ' dist-tags --json').toString());
            out[name] = { version: info.version, tarball: info.dist?.tarball, gitHead: info.gitHead, distTags: tags };
          }
          process.stdout.write('info='+JSON.stringify(out));
          " >> $GITHUB_OUTPUT
        env:
          VERSIONS: ${{ steps.versions.outputs.versions }}

      - name: Verify dist-tags (next)
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.dry_run) }}
        run: |
          node -e "
          const { execSync } = require('child_process');
          const versions = JSON.parse(process.env.VERSIONS || '{}');
          const pkgs = ['extension','extension-create','extension-develop'];
          for (const name of pkgs) {
            const expected = versions[name];
            if (!expected) continue;
            const tags = JSON.parse(execSync('npm view ' + name + ' dist-tags --json').toString());
            if (tags.next !== expected) {
              console.error(`[next] Dist-tag mismatch for ${name}: next=${tags.next} expected=${expected}`);
              process.exit(1);
            }
          }
          console.log('Next dist-tags verified.');
          "
        env:
          VERSIONS: ${{ steps.versions.outputs.versions }}

      - name: Create deployment (next)
        if: ${{ !(github.event_name == 'workflow_dispatch' && inputs.dry_run) }}
        uses: actions/github-script@v7
        env:
          VERSIONS: ${{ steps.versions.outputs.versions }}
          NPM_INFO: ${{ steps.npm.outputs.info }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const payload = {
              channel: 'next',
              distTag: 'next',
              versions: JSON.parse(process.env.VERSIONS || '{}'),
              npm: JSON.parse(process.env.NPM_INFO || '{}')
            };
            const ref = context.sha;
            const dep = await github.rest.repos.createDeployment({
              owner, repo, ref,
              environment: 'next',
              auto_merge: false,
              required_contexts: [],
              transient_environment: true,
              description: `Published to npm (next)`,
              payload: JSON.stringify(payload)
            });
            const ext = payload.versions['extension'];
            const envUrl = ext ? `https://www.npmjs.com/package/extension/v/${ext}` : undefined;
            const desc = `extension ${payload.versions['extension']}, extension-create ${payload.versions['extension-create']}, extension-develop ${payload.versions['extension-develop']}`;
            await github.rest.repos.createDeploymentStatus({
              owner, repo, deployment_id: dep.data.id,
              state: 'success',
              log_url: `${context.serverUrl}/${owner}/${repo}/actions/runs/${context.runId}`,
              environment_url: envUrl,
              description: desc
            })


