name: Develop – Tests

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  test-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install workspace deps
        run: pnpm install --frozen-lockfile

      - name: Build extension-develop
        run: pnpm --filter extension-develop compile

      - name: Run tests for extension-develop
        run: pnpm -F extension-develop test


