name: Extension Preview

on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.x'

permissions:
  contents: read

jobs:
  preview:
    name: Build Preview
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Build Preview
        run: |
          pnpm compile
          # TODO: Uncomment when preview command is ready
          # pnpm test:preview
