name: Release Preview

on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.x'

permissions:
  contents: read

jobs:
  release-preview:
    name: Deploy Release Preview
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Build and Deploy
        run: |
          pnpm compile
          pnpx pkg-pr-new publish './programs/*'